[package]
name = "nextsycl"
description = "The command line: info, check, generate, serve"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ns-gguf.workspace = true
ns-model.workspace = true
ns-core.workspace = true
ns-engine.workspace = true
ns-tok.workspace = true
